language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - python setup.py install  >/dev/null
  - python -c 'import jmatch'
  - nosetests --with-coverage --cover-package=json-match
after_success:
  - coveralls
